### ISSUE TITLE
Workaround for error during "waiting for missing files"

### ISSUE THREAD

**Issue by eclarke** [eclarke/sunbeam#13]
Sometimes Snakemake raises a MissingFilesError, and then encounters another error, when handling missing files. This prevents the job from returning and prevents the workflow from continuing. It seems to be a bug because re-running it often completes without error. We need to know why this occurs, but the fix may actually need to happen on Snakemake's end.

**Comment by varunaggarwala** [comment]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/avarun/miniconda3/envs/sunbeam/lib/python3.5/site-packages/snakemake/dag.py", line 257, in check_and_touch_output
    wait_for_files(expanded_output, latency_wait=wait)
  File "/home/avarun/miniconda3/envs/sunbeam/lib/python3.5/site-packages/snakemake/io.py", line 368, in wait_for_files
    latency_wait, "\n".join(get_missing())))
OSError: Missing files after 5 seconds:
/home/avarun/sunbeam/sunbeam_clarke_sarcoid/qc/cutadapt/Pulm16BALd_S14_R2.fastq
/home/avarun/sunbeam/sunbeam_clarke_sarcoid/qc/cutadapt/Pulm16BALd_S14_R1.fastq

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/avarun/miniconda3/envs/sunbeam/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/avarun/miniconda3/envs/sunbeam/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/avarun/miniconda3/envs/sunbeam/lib/python3.5/site-packages/snakemake/executors.py", line 554, in _wait_for_jobs
    self.finish_job(active_job.job)
  File "/home/avarun/miniconda3/envs/sunbeam/lib/python3.5/site-packages/snakemake/executors.py", line 463, in finish_job
    super().finish_job(job, upload_remote=False)
  File "/home/avarun/miniconda3/envs/sunbeam/lib/python3.5/site-packages/snakemake/executors.py", line 153, in finish_job
    super().finish_job(job, upload_remote=upload_remote)
  File "/home/avarun/miniconda3/envs/sunbeam/lib/python3.5/site-packages/snakemake/executors.py", line 111, in finish_job
    self.dag.check_and_touch_output(job, wait=self.latency_wait)
  File "/home/avarun/miniconda3/envs/sunbeam/lib/python3.5/site-packages/snakemake/dag.py", line 259, in check_and_touch_output
    raise MissingOutputException(str(e), rule=job.rule)
snakemake.exceptions.MissingOutputException: Missing files after 5 seconds:
/home/avarun/sunbeam/sunbeam_clarke_sarcoid/qc/cutadapt/Pulm16BALd_S14_R2.fastq
/home/avarun/sunbeam/sunbeam_clarke_sarcoid/qc/cutadapt/Pulm16BALd_S14_R1.fastq

**Comment by eclarke** [comment]
Somebody has had the same issue on the Snakemake repo: https://bitbucket.org/snakemake/snakemake/issues/389/persistent-and-erroneous

It appears that increasing the wait time (`-w 90`) may reduce or resolve this.

Erik Clarke
Genomics and Computational Biology
University of Pennsylvania

**Comment by varunaggarwala** [comment]
Thanks Erik.
I am not seeing this error now with the wait option.
Varun
